### ISSUE TITLE
[Bug]: Issue hooks.useLocation preview is not displaying correctly

### ISSUE THREAD

**Issue by lydamian** [damien-schneider/cuicui#49]
### Feature Description

See https://cuicui.day/hooks/use-location
<img width="1106" alt="Screenshot 2024-10-29 at 11 15 55 AM" src="https://github.com/user-attachments/assets/5d9d78d3-d693-404d-92df-7be122540a79">

### Additional Context

Additional details here...

### Before Submitting

- [X] I've researched and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by damien-schneider** [comment]
Issue has been fixed in this PR : #51 And it is now in production ! Thanks @lydamian for reporting this ! 🙏

**Comment by lydamian** [comment]
Thank you! amazing stuff
